// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://cvtaoohucdujmkyydfqi.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImN2dGFvb2h1Y2R1am1reXlkZnFpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTM1ODc2MzYsImV4cCI6MjA2OTE2MzYzNn0.dE9NOjJ-WqhVrlMeQ0DA3X3gOUzoxt6SKz0-Ngua8Go";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});